site_name: Specification (pre-draft)
docs_dir: system-design

nav:
  - What is Margo?: index.md
  - Personas & Definitions:
      - personas-and-definitions/personas.md
      - personas-and-definitions/persona-examples.md
      - personas-and-definitions/technical-lexicon.md
      - personas-and-definitions/software-composition.md
  - Overview:
      - overview/envisioned-system-design.md
      - overview/workloads.md
      - overview/workload-fleet-management.md
      - overview/edge-compute-devices.md
      - overview/workload-observability.md
  - Concepts:
      - Workloads:
          - concepts/workloads/application-package.md
          - concepts/workloads/application-registry.md
          - concepts/workloads/publishing-workload-observability-data.md
          - concepts/workloads/local-registries.md
      - Workload Fleet Managers:
          - concepts/workload-fleet-managers/device-capabilities.md
          - concepts/workload-fleet-managers/workload-deployment.md
          - concepts/workload-fleet-managers/consuming-workload-observability-data.md
      - Edge Compute Devices:
          - concepts/edge-compute-devices/devices.md
          - concepts/edge-compute-devices/collecting-workload-observability-data.md
  - Specification (pre-draft):
      - Margo Management Interface:
          - margo-api-reference/workload-api/api-req-security-details.md
          - margo-api-reference/workload-api/onboarding-api/device-onboarding.md
          - margo-api-reference/workload-api/onboarding-api/rootca-download.md
          - margo-api-reference/workload-api/device-api/device-capabilities.md
          - margo-api-reference/workload-api/desired-state-api/desired-state.md
          - margo-api-reference/workload-api/device-api/deployment-status.md
      - Application Package:
          - specification/application-package/application-description.md
      - Margo Devices:
          - specification/margo-devices/device-requirements.md
      #- Observability: 
  - Make a Contribution:
      - make-a-contribution/contributing.md

theme:
  name: material
  features:
    #- navigation.tabs
    #- navigation.settings
    #- navigation.top
    #- navigation.sections
    - navigation.tracking
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy
  language: en
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: assets/margo_white.svg
  favicon: assets/favicon.ico
  palette:
    scheme: margo

markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format      

extra_css:
  - css/margo.css

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
  generator: true
  homepage: https://margo.org
  copyright: Copyright &copy; 2024 Margo
  reponame: !ENV [GITHUB_REPOSITORY, "margo/specification"]
  commit: !ENV [GITHUB_SHA, "<unknown>"]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/margo
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/margo_project
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/margoproject/about/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Margoinitiative
    - icon: fontawesome/brands/discord
      link: http://chat.margo.org/

plugins:
  - search
  - markdownextradata:
      jinja_options:
        variable_start_string: =@=
        variable_end_string: =@=
  - privacy
