site_name: Specification (pre-draft)
docs_dir: system-design

nav:
  - What is Margo?: index.md
  - Personas & Definitions:
      - margo-overview/personas.md
      - margo-overview/personas-extended.md
      - margo-overview/technical-lexicon.md
      - margo-overview/software-composition.md
  - Overview:
      - margo-overview/introduction-system-design.md
      - margo-overview/application-package-overview.md
      - margo-overview/workload-management-interface-overview.md
      - margo-overview/devices-overview.md
      - margo-overview/workload-observability-overview.md
  - Concepts:
      - Workloads:
          - app-interoperability/application-package-definition.md
          - app-interoperability/workload-orch-to-app-reg-interaction.md # = Application Registry
          - app-interoperability/publishing-workload-observability-data.md
          - app-interoperability/local-registries.md
      - Workload Fleet Managers:
          - fleet-management/workload/management-interface-requirements.md
          - fleet-management/workload/workload-fleet-management-edge-onboarding.md
          - fleet-management/workload/device-capability-reporting.md
          - fleet-management/workload/workload-deployment.md
          - fleet-management/workload/consuming-workload-observability-data.md
      - Edge Compute Devices:
          - device-interoperability/device-requirements.md
          - device-interoperability/collecting-workload-observability-data.md
  - Technical References:
      - Margo Management Interface:
          - margo-api-reference/margo-api-specification.md
          - margo-api-reference/workload-api/desired-state-api/desired-state.md
          - margo-api-reference/workload-api/device-api/device-capabilities.md
          - margo-api-reference/workload-api/device-api/deployment-status.md
          - margo-api-reference/workload-api/onboarding-api/device-onboarding.md
          - margo-api-reference/workload-api/onboarding-api/rootca-download.md
      - Application Package Definition:
          - margo-api-reference/workload-api/application-package-api/application-description.md
      #- Observability: 
  - Make a Contribution:
      - how-to-contribute/contribution-tutorial.md
      - how-to-contribute/contribution-navigation.md

theme:
  name: material
  features:
    #- navigation.tabs
    #- navigation.settings
    #- navigation.top
    #- navigation.sections
    - navigation.tracking
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy
  language: en
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: assets/margo_white.svg
  favicon: assets/favicon.ico
  palette:
    scheme: margo

markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format      

extra_css:
  - css/margo.css

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
  generator: true
  homepage: https://margo.org
  copyright: Copyright &copy; 2024 Margo
  reponame: !ENV [GITHUB_REPOSITORY, "margo/specification"]
  commit: !ENV [GITHUB_SHA, "<unknown>"]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/margo
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/margo_project
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/margoproject/about/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Margoinitiative
    - icon: fontawesome/brands/discord
      link: http://chat.margo.org/

plugins:
  - search
  - markdownextradata:
      jinja_options:
        variable_start_string: =@=
        variable_end_string: =@=
  - privacy
