services:
  general_website_content:
    build:
      context: ../
      dockerfile: ./.devcontainer/.dockerfile
    container_name: general_website_content
    ports:
      - 8000:8000
    volumes:
      - ..:/home/vscode/docs/
    tty: true           # <- keeps container running
    networks:
      - general_website_content_network

networks: 
  general_website_content_network:
    driver: bridge